# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

# This is a reminder that you are using a generated .pro file.
# Remove it when you are finished editing this file.
message("You are running qmake on a generated .pro file. This may not work!")


HEADERS += ./drukuj.h \
    ./eksportuj.h \
    ./film_ftbl_class.h \
    ./IntWiz.h \
    ./mainwindow.h \
    ./oprog.h \
    ./resource3.h \
    ./Unmngd.h \
    ./wyszukaj.h \
    ./ImpBFNETWiz.h
SOURCES += ./drukuj.cpp \
    ./eksportuj.cpp \
    ./IntWiz.cpp \
    ./main.cpp \
    ./mainwindow.cpp \
    ./oprog.cpp \
    ./wyszukaj.cpp \
    ./ImpBFNETWiz.cpp
FORMS += ./drukuj.ui \
    ./eksportuj.ui \
    ./IntWiz.ui \
    ./mainwindow.ui \
    ./oprog.ui \
    ./wyszukaj.ui \
    ./ImpBFNETWiz.ui
TRANSLATIONS += ./bf_en.ts
RESOURCES += ./res.qrc
