/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 4.8.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QComboBox>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QStatusBar>
#include <QtGui/QTabWidget>
#include <QtGui/QTableWidget>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionOtw_rz_Utw_rz_baze_danych;
    QAction *actionEksportuj;
    QAction *actionWyszukaj;
    QAction *actionKoniec;
    QAction *actionDrukuj;
    QAction *actionPomoc;
    QAction *actionSprawd_aktualizacje;
    QAction *actionO_programie;
    QWidget *centralWidget;
    QPushButton *pushButton_LoadPic;
    QPushButton *pushButton_DelPic;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLineEdit *lineEdit_Tytul;
    QLineEdit *lineEdit_TytulOrig;
    QLineEdit *lineEdit_Gatunek;
    QTabWidget *tabWidget;
    QWidget *tab;
    QLabel *label_45;
    QTableWidget *tableWidget_OC;
    QPushButton *pushButton_OC_New;
    QPushButton *pushButton_OC_Save;
    QPushButton *pushButton_OC_Del;
    QGroupBox *groupBox_6;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QLineEdit *lineEdit_OC_OW_SD;
    QLineEdit *lineEdit_OC_OW_Obs;
    QLineEdit *lineEdit__OC_OW_All;
    QLabel *label_49;
    QLabel *label_50;
    QLineEdit *lineEdit__OC_OW_Zdj;
    QLineEdit *lineEdit__OC_OW_WA;
    QWidget *obsada;
    QTableWidget *tableWidget_Obsada;
    QPushButton *pushButton_OBSave;
    QPushButton *pushButton_OBDel;
    QPushButton *pushButton_OB_new;
    QWidget *Produkcja;
    QLabel *label_6;
    QTableWidget *tableWidget_Prod;
    QPushButton *pushButton_PRODSave;
    QPushButton *pushButton_PRODDel;
    QTableWidget *tableWidget_Dystr;
    QLabel *label_7;
    QPushButton *pushButton_DYSTSave;
    QPushButton *pushButton_DYSTDel;
    QPushButton *pushButto_P_New;
    QPushButton *pushButton_D_New;
    QWidget *DOE;
    QGroupBox *groupBox;
    QLabel *label_8;
    QLineEdit *lineEdit_DOE_W_Imie;
    QLabel *label_9;
    QLineEdit *lineEdit_DOE_W_Nazw;
    QLabel *label_10;
    QLineEdit *lineEdit_DOE_W_Adres;
    QGroupBox *groupBox_2;
    QLabel *label_11;
    QLineEdit *lineEdit_DOE_S_Nazwa;
    QLabel *label_12;
    QLineEdit *lineEdit_DOE_S_Tel;
    QLabel *label_13;
    QLineEdit *lineEdit_DOE_S_Adres;
    QLabel *label_14;
    QLineEdit *lineEdit_DOE_S_WWW;
    QLabel *label_15;
    QLineEdit *lineEdit_DOE_S_Fax;
    QLabel *label_16;
    QLineEdit *lineEdit_DOE_S_Email;
    QLabel *label_17;
    QLineEdit *lineEdit_DOE_Cena;
    QLabel *label_18;
    QLineEdit *lineEdit_DOE_Wakt;
    QLabel *label_19;
    QLineEdit *lineEdit_DOE_DataZak;
    QLabel *label_20;
    QLineEdit *lineEdit_DOE_DataUtr;
    QLabel *label_21;
    QLineEdit *lineEdit_DOE_DataSkat;
    QLabel *label_22;
    QLineEdit *lineEdit_DOE_NrKat;
    QLabel *label_23;
    QLineEdit *lineEdit_DOE_Nosnik;
    QWidget *IOF;
    QLabel *label_24;
    QLineEdit *lineEdit_RokProd;
    QLabel *label_25;
    QLineEdit *lineEdit_CzasProj;
    QLabel *label_26;
    QLineEdit *lineEdit_SysKodObr;
    QLabel *label_27;
    QLineEdit *lineEdit_DataPrem;
    QLabel *label_28;
    QLineEdit *lineEdit_FormWysw;
    QLabel *label_29;
    QLineEdit *lineEdit_JezLekt;
    QLabel *label_30;
    QLineEdit *lineEdit_JezNap;
    QGroupBox *groupBox_3;
    QLabel *label_31;
    QLineEdit *lineEdit_KodVidNazwa;
    QLabel *label_32;
    QLineEdit *lineEdit_KodVidTyp;
    QLabel *label_33;
    QLineEdit *lineEdit_KodVidWersja;
    QGroupBox *groupBox_4;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLineEdit *lineEdit_KodAudNazwa;
    QLineEdit *lineEdit_KodAudTyp;
    QLineEdit *lineEdit_KodAudWersja;
    QGroupBox *groupBox_5;
    QLabel *label_37;
    QLineEdit *lineEdit_ZabNazwa;
    QLabel *label_38;
    QLineEdit *lineEdit_ZabTyp;
    QLabel *label_39;
    QLineEdit *lineEdit_ZabWersja;
    QLabel *label_40;
    QLineEdit *lineEdit_KrajProd;
    QTableWidget *tableWidget_IOF_LZ;
    QLabel *label_41;
    QPushButton *pushButton_LZSave;
    QPushButton *pushButton_LZDel;
    QPushButton *pushButton_LZ_New;
    QWidget *BIBLIO;
    QTableWidget *tableWidget_BIBLIO_WYPIN;
    QLabel *label_42;
    QPushButton *pushButton_BIBLIOWYPISave;
    QPushButton *pushButton_BIBLIOWYPINDel;
    QTableWidget *tableWidget_BIBLIO_WYPODIN;
    QPushButton *pushButton_BIBLIOWYPODINSave;
    QPushButton *pushButton_BIBLIOWYPODINDel;
    QLabel *label_43;
    QPushButton *pushButton_B_WYPIN_New;
    QPushButton *pushButton_B_WYPODIN_New;
    QPushButton *pushButton_First;
    QPushButton *pushButton_Prev;
    QPushButton *pushButton_Next;
    QPushButton *pushButton_Last;
    QPushButton *pushButton_New;
    QPushButton *pushButton_Save;
    QPushButton *pushButton_Del;
    QPushButton *pushButton_IntWiz;
    QLabel *label_4;
    QLineEdit *lineEdit_RecNo;
    QLabel *label_5;
    QLineEdit *lineEdit_RecCount;
    QLabel *label_44;
    QLineEdit *lineEdit_ID;
    QLabel *label_PicFront;
    QComboBox *comboBox_GatSel;
    QMenuBar *menuBar;
    QMenu *menuOperacje;
    QMenu *menuPomoc;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(769, 529);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/new/prefix1/MK_LOGO.ico"), QSize(), QIcon::Normal, QIcon::Off);
        MainWindow->setWindowIcon(icon);
        actionOtw_rz_Utw_rz_baze_danych = new QAction(MainWindow);
        actionOtw_rz_Utw_rz_baze_danych->setObjectName(QString::fromUtf8("actionOtw_rz_Utw_rz_baze_danych"));
        actionEksportuj = new QAction(MainWindow);
        actionEksportuj->setObjectName(QString::fromUtf8("actionEksportuj"));
        actionWyszukaj = new QAction(MainWindow);
        actionWyszukaj->setObjectName(QString::fromUtf8("actionWyszukaj"));
        actionKoniec = new QAction(MainWindow);
        actionKoniec->setObjectName(QString::fromUtf8("actionKoniec"));
        actionDrukuj = new QAction(MainWindow);
        actionDrukuj->setObjectName(QString::fromUtf8("actionDrukuj"));
        actionPomoc = new QAction(MainWindow);
        actionPomoc->setObjectName(QString::fromUtf8("actionPomoc"));
        actionSprawd_aktualizacje = new QAction(MainWindow);
        actionSprawd_aktualizacje->setObjectName(QString::fromUtf8("actionSprawd_aktualizacje"));
        actionO_programie = new QAction(MainWindow);
        actionO_programie->setObjectName(QString::fromUtf8("actionO_programie"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        pushButton_LoadPic = new QPushButton(centralWidget);
        pushButton_LoadPic->setObjectName(QString::fromUtf8("pushButton_LoadPic"));
        pushButton_LoadPic->setGeometry(QRect(9, 180, 58, 23));
        pushButton_DelPic = new QPushButton(centralWidget);
        pushButton_DelPic->setObjectName(QString::fromUtf8("pushButton_DelPic"));
        pushButton_DelPic->setGeometry(QRect(89, 180, 64, 23));
        label = new QLabel(centralWidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(165, 9, 46, 13));
        label_2 = new QLabel(centralWidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(165, 30, 79, 16));
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(168, 57, 46, 13));
        lineEdit_Tytul = new QLineEdit(centralWidget);
        lineEdit_Tytul->setObjectName(QString::fromUtf8("lineEdit_Tytul"));
        lineEdit_Tytul->setGeometry(QRect(243, 9, 328, 19));
        lineEdit_TytulOrig = new QLineEdit(centralWidget);
        lineEdit_TytulOrig->setObjectName(QString::fromUtf8("lineEdit_TytulOrig"));
        lineEdit_TytulOrig->setGeometry(QRect(243, 30, 328, 19));
        lineEdit_Gatunek = new QLineEdit(centralWidget);
        lineEdit_Gatunek->setObjectName(QString::fromUtf8("lineEdit_Gatunek"));
        lineEdit_Gatunek->setGeometry(QRect(243, 51, 241, 19));
        tabWidget = new QTabWidget(centralWidget);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tabWidget->setGeometry(QRect(168, 75, 589, 355));
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        label_45 = new QLabel(tab);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(3, 3, 142, 16));
        tableWidget_OC = new QTableWidget(tab);
        if (tableWidget_OC->columnCount() < 7)
            tableWidget_OC->setColumnCount(7);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidget_OC->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidget_OC->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidget_OC->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidget_OC->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidget_OC->setHorizontalHeaderItem(4, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidget_OC->setHorizontalHeaderItem(5, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidget_OC->setHorizontalHeaderItem(6, __qtablewidgetitem6);
        tableWidget_OC->setObjectName(QString::fromUtf8("tableWidget_OC"));
        tableWidget_OC->setGeometry(QRect(3, 18, 577, 181));
        tableWidget_OC->setEditTriggers(QAbstractItemView::DoubleClicked);
        tableWidget_OC->setTabKeyNavigation(false);
        tableWidget_OC->setProperty("showDropIndicator", QVariant(false));
        tableWidget_OC->setDragDropOverwriteMode(false);
        tableWidget_OC->setSelectionBehavior(QAbstractItemView::SelectRows);
        tableWidget_OC->horizontalHeader()->setDefaultSectionSize(150);
        pushButton_OC_New = new QPushButton(tab);
        pushButton_OC_New->setObjectName(QString::fromUtf8("pushButton_OC_New"));
        pushButton_OC_New->setGeometry(QRect(237, 201, 75, 23));
        pushButton_OC_Save = new QPushButton(tab);
        pushButton_OC_Save->setObjectName(QString::fromUtf8("pushButton_OC_Save"));
        pushButton_OC_Save->setGeometry(QRect(318, 201, 75, 23));
        pushButton_OC_Del = new QPushButton(tab);
        pushButton_OC_Del->setObjectName(QString::fromUtf8("pushButton_OC_Del"));
        pushButton_OC_Del->setGeometry(QRect(504, 201, 75, 23));
        groupBox_6 = new QGroupBox(tab);
        groupBox_6->setObjectName(QString::fromUtf8("groupBox_6"));
        groupBox_6->setGeometry(QRect(6, 234, 574, 85));
        label_46 = new QLabel(groupBox_6);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(9, 15, 100, 16));
        label_47 = new QLabel(groupBox_6);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(9, 36, 46, 13));
        label_48 = new QLabel(groupBox_6);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(9, 57, 46, 13));
        lineEdit_OC_OW_SD = new QLineEdit(groupBox_6);
        lineEdit_OC_OW_SD->setObjectName(QString::fromUtf8("lineEdit_OC_OW_SD"));
        lineEdit_OC_OW_SD->setGeometry(QRect(108, 12, 113, 20));
        lineEdit_OC_OW_Obs = new QLineEdit(groupBox_6);
        lineEdit_OC_OW_Obs->setObjectName(QString::fromUtf8("lineEdit_OC_OW_Obs"));
        lineEdit_OC_OW_Obs->setGeometry(QRect(108, 33, 113, 20));
        lineEdit__OC_OW_All = new QLineEdit(groupBox_6);
        lineEdit__OC_OW_All->setObjectName(QString::fromUtf8("lineEdit__OC_OW_All"));
        lineEdit__OC_OW_All->setGeometry(QRect(108, 54, 113, 20));
        label_49 = new QLabel(groupBox_6);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(231, 15, 46, 13));
        label_50 = new QLabel(groupBox_6);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(231, 33, 106, 16));
        lineEdit__OC_OW_Zdj = new QLineEdit(groupBox_6);
        lineEdit__OC_OW_Zdj->setObjectName(QString::fromUtf8("lineEdit__OC_OW_Zdj"));
        lineEdit__OC_OW_Zdj->setGeometry(QRect(339, 12, 113, 20));
        lineEdit__OC_OW_WA = new QLineEdit(groupBox_6);
        lineEdit__OC_OW_WA->setObjectName(QString::fromUtf8("lineEdit__OC_OW_WA"));
        lineEdit__OC_OW_WA->setGeometry(QRect(339, 33, 113, 20));
        tabWidget->addTab(tab, QString());
        obsada = new QWidget();
        obsada->setObjectName(QString::fromUtf8("obsada"));
        tableWidget_Obsada = new QTableWidget(obsada);
        if (tableWidget_Obsada->columnCount() < 4)
            tableWidget_Obsada->setColumnCount(4);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidget_Obsada->setHorizontalHeaderItem(0, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableWidget_Obsada->setHorizontalHeaderItem(1, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableWidget_Obsada->setHorizontalHeaderItem(2, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tableWidget_Obsada->setHorizontalHeaderItem(3, __qtablewidgetitem10);
        tableWidget_Obsada->setObjectName(QString::fromUtf8("tableWidget_Obsada"));
        tableWidget_Obsada->setGeometry(QRect(6, 6, 574, 259));
        tableWidget_Obsada->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOn);
        tableWidget_Obsada->setEditTriggers(QAbstractItemView::DoubleClicked);
        tableWidget_Obsada->setTabKeyNavigation(false);
        tableWidget_Obsada->setProperty("showDropIndicator", QVariant(false));
        tableWidget_Obsada->setDragDropOverwriteMode(false);
        tableWidget_Obsada->setSelectionBehavior(QAbstractItemView::SelectRows);
        tableWidget_Obsada->horizontalHeader()->setDefaultSectionSize(200);
        pushButton_OBSave = new QPushButton(obsada);
        pushButton_OBSave->setObjectName(QString::fromUtf8("pushButton_OBSave"));
        pushButton_OBSave->setGeometry(QRect(339, 267, 75, 23));
        pushButton_OBDel = new QPushButton(obsada);
        pushButton_OBDel->setObjectName(QString::fromUtf8("pushButton_OBDel"));
        pushButton_OBDel->setGeometry(QRect(507, 267, 75, 23));
        pushButton_OB_new = new QPushButton(obsada);
        pushButton_OB_new->setObjectName(QString::fromUtf8("pushButton_OB_new"));
        pushButton_OB_new->setGeometry(QRect(261, 267, 75, 23));
        tabWidget->addTab(obsada, QString());
        Produkcja = new QWidget();
        Produkcja->setObjectName(QString::fromUtf8("Produkcja"));
        label_6 = new QLabel(Produkcja);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(6, 3, 46, 13));
        tableWidget_Prod = new QTableWidget(Produkcja);
        if (tableWidget_Prod->columnCount() < 8)
            tableWidget_Prod->setColumnCount(8);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableWidget_Prod->setHorizontalHeaderItem(0, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        tableWidget_Prod->setHorizontalHeaderItem(1, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        tableWidget_Prod->setHorizontalHeaderItem(2, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        tableWidget_Prod->setHorizontalHeaderItem(3, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tableWidget_Prod->setHorizontalHeaderItem(4, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        tableWidget_Prod->setHorizontalHeaderItem(5, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        tableWidget_Prod->setHorizontalHeaderItem(6, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        tableWidget_Prod->setHorizontalHeaderItem(7, __qtablewidgetitem18);
        tableWidget_Prod->setObjectName(QString::fromUtf8("tableWidget_Prod"));
        tableWidget_Prod->setGeometry(QRect(3, 21, 577, 115));
        tableWidget_Prod->setEditTriggers(QAbstractItemView::DoubleClicked);
        tableWidget_Prod->setTabKeyNavigation(false);
        tableWidget_Prod->setProperty("showDropIndicator", QVariant(false));
        tableWidget_Prod->setDragDropOverwriteMode(false);
        tableWidget_Prod->setSelectionBehavior(QAbstractItemView::SelectRows);
        pushButton_PRODSave = new QPushButton(Produkcja);
        pushButton_PRODSave->setObjectName(QString::fromUtf8("pushButton_PRODSave"));
        pushButton_PRODSave->setGeometry(QRect(306, 138, 75, 23));
        pushButton_PRODDel = new QPushButton(Produkcja);
        pushButton_PRODDel->setObjectName(QString::fromUtf8("pushButton_PRODDel"));
        pushButton_PRODDel->setGeometry(QRect(504, 138, 75, 23));
        tableWidget_Dystr = new QTableWidget(Produkcja);
        if (tableWidget_Dystr->columnCount() < 8)
            tableWidget_Dystr->setColumnCount(8);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        tableWidget_Dystr->setHorizontalHeaderItem(0, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        tableWidget_Dystr->setHorizontalHeaderItem(1, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        tableWidget_Dystr->setHorizontalHeaderItem(2, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        tableWidget_Dystr->setHorizontalHeaderItem(3, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        tableWidget_Dystr->setHorizontalHeaderItem(4, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        tableWidget_Dystr->setHorizontalHeaderItem(5, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        tableWidget_Dystr->setHorizontalHeaderItem(6, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        tableWidget_Dystr->setHorizontalHeaderItem(7, __qtablewidgetitem26);
        tableWidget_Dystr->setObjectName(QString::fromUtf8("tableWidget_Dystr"));
        tableWidget_Dystr->setGeometry(QRect(3, 162, 574, 109));
        tableWidget_Dystr->setEditTriggers(QAbstractItemView::DoubleClicked);
        tableWidget_Dystr->setTabKeyNavigation(false);
        tableWidget_Dystr->setProperty("showDropIndicator", QVariant(false));
        tableWidget_Dystr->setDragDropOverwriteMode(false);
        tableWidget_Dystr->setSelectionBehavior(QAbstractItemView::SelectRows);
        label_7 = new QLabel(Produkcja);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(6, 144, 67, 16));
        pushButton_DYSTSave = new QPushButton(Produkcja);
        pushButton_DYSTSave->setObjectName(QString::fromUtf8("pushButton_DYSTSave"));
        pushButton_DYSTSave->setGeometry(QRect(306, 273, 75, 23));
        pushButton_DYSTDel = new QPushButton(Produkcja);
        pushButton_DYSTDel->setObjectName(QString::fromUtf8("pushButton_DYSTDel"));
        pushButton_DYSTDel->setGeometry(QRect(504, 273, 75, 23));
        pushButto_P_New = new QPushButton(Produkcja);
        pushButto_P_New->setObjectName(QString::fromUtf8("pushButto_P_New"));
        pushButto_P_New->setGeometry(QRect(231, 138, 75, 23));
        pushButton_D_New = new QPushButton(Produkcja);
        pushButton_D_New->setObjectName(QString::fromUtf8("pushButton_D_New"));
        pushButton_D_New->setGeometry(QRect(231, 273, 75, 23));
        tabWidget->addTab(Produkcja, QString());
        DOE = new QWidget();
        DOE->setObjectName(QString::fromUtf8("DOE"));
        groupBox = new QGroupBox(DOE);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(3, 6, 574, 67));
        label_8 = new QLabel(groupBox);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(9, 18, 46, 13));
        lineEdit_DOE_W_Imie = new QLineEdit(groupBox);
        lineEdit_DOE_W_Imie->setObjectName(QString::fromUtf8("lineEdit_DOE_W_Imie"));
        lineEdit_DOE_W_Imie->setGeometry(QRect(60, 15, 217, 20));
        label_9 = new QLabel(groupBox);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(285, 18, 46, 13));
        lineEdit_DOE_W_Nazw = new QLineEdit(groupBox);
        lineEdit_DOE_W_Nazw->setObjectName(QString::fromUtf8("lineEdit_DOE_W_Nazw"));
        lineEdit_DOE_W_Nazw->setGeometry(QRect(336, 15, 229, 20));
        label_10 = new QLabel(groupBox);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(9, 42, 46, 13));
        lineEdit_DOE_W_Adres = new QLineEdit(groupBox);
        lineEdit_DOE_W_Adres->setObjectName(QString::fromUtf8("lineEdit_DOE_W_Adres"));
        lineEdit_DOE_W_Adres->setGeometry(QRect(60, 39, 292, 20));
        groupBox_2 = new QGroupBox(DOE);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(6, 84, 571, 94));
        label_11 = new QLabel(groupBox_2);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(9, 18, 46, 13));
        lineEdit_DOE_S_Nazwa = new QLineEdit(groupBox_2);
        lineEdit_DOE_S_Nazwa->setObjectName(QString::fromUtf8("lineEdit_DOE_S_Nazwa"));
        lineEdit_DOE_S_Nazwa->setGeometry(QRect(60, 15, 289, 20));
        label_12 = new QLabel(groupBox_2);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(381, 18, 46, 13));
        lineEdit_DOE_S_Tel = new QLineEdit(groupBox_2);
        lineEdit_DOE_S_Tel->setObjectName(QString::fromUtf8("lineEdit_DOE_S_Tel"));
        lineEdit_DOE_S_Tel->setGeometry(QRect(435, 15, 124, 20));
        label_13 = new QLabel(groupBox_2);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(9, 42, 46, 13));
        lineEdit_DOE_S_Adres = new QLineEdit(groupBox_2);
        lineEdit_DOE_S_Adres->setObjectName(QString::fromUtf8("lineEdit_DOE_S_Adres"));
        lineEdit_DOE_S_Adres->setGeometry(QRect(60, 39, 289, 20));
        label_14 = new QLabel(groupBox_2);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(9, 66, 79, 16));
        lineEdit_DOE_S_WWW = new QLineEdit(groupBox_2);
        lineEdit_DOE_S_WWW->setObjectName(QString::fromUtf8("lineEdit_DOE_S_WWW"));
        lineEdit_DOE_S_WWW->setGeometry(QRect(81, 63, 268, 20));
        label_15 = new QLabel(groupBox_2);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(381, 42, 46, 13));
        lineEdit_DOE_S_Fax = new QLineEdit(groupBox_2);
        lineEdit_DOE_S_Fax->setObjectName(QString::fromUtf8("lineEdit_DOE_S_Fax"));
        lineEdit_DOE_S_Fax->setGeometry(QRect(435, 39, 124, 20));
        label_16 = new QLabel(groupBox_2);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(381, 66, 46, 13));
        lineEdit_DOE_S_Email = new QLineEdit(groupBox_2);
        lineEdit_DOE_S_Email->setObjectName(QString::fromUtf8("lineEdit_DOE_S_Email"));
        lineEdit_DOE_S_Email->setGeometry(QRect(435, 63, 124, 20));
        label_17 = new QLabel(DOE);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(15, 189, 46, 13));
        lineEdit_DOE_Cena = new QLineEdit(DOE);
        lineEdit_DOE_Cena->setObjectName(QString::fromUtf8("lineEdit_DOE_Cena"));
        lineEdit_DOE_Cena->setGeometry(QRect(105, 186, 76, 20));
        label_18 = new QLabel(DOE);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(15, 213, 88, 16));
        lineEdit_DOE_Wakt = new QLineEdit(DOE);
        lineEdit_DOE_Wakt->setObjectName(QString::fromUtf8("lineEdit_DOE_Wakt"));
        lineEdit_DOE_Wakt->setGeometry(QRect(105, 210, 76, 20));
        label_19 = new QLabel(DOE);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(15, 237, 73, 16));
        lineEdit_DOE_DataZak = new QLineEdit(DOE);
        lineEdit_DOE_DataZak->setObjectName(QString::fromUtf8("lineEdit_DOE_DataZak"));
        lineEdit_DOE_DataZak->setGeometry(QRect(105, 234, 97, 20));
        label_20 = new QLabel(DOE);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(219, 189, 58, 16));
        lineEdit_DOE_DataUtr = new QLineEdit(DOE);
        lineEdit_DOE_DataUtr->setObjectName(QString::fromUtf8("lineEdit_DOE_DataUtr"));
        lineEdit_DOE_DataUtr->setGeometry(QRect(324, 186, 113, 20));
        label_21 = new QLabel(DOE);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(219, 213, 106, 16));
        lineEdit_DOE_DataSkat = new QLineEdit(DOE);
        lineEdit_DOE_DataSkat->setObjectName(QString::fromUtf8("lineEdit_DOE_DataSkat"));
        lineEdit_DOE_DataSkat->setGeometry(QRect(324, 210, 113, 20));
        label_22 = new QLabel(DOE);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(219, 237, 79, 16));
        lineEdit_DOE_NrKat = new QLineEdit(DOE);
        lineEdit_DOE_NrKat->setObjectName(QString::fromUtf8("lineEdit_DOE_NrKat"));
        lineEdit_DOE_NrKat->setGeometry(QRect(324, 234, 205, 20));
        label_23 = new QLabel(DOE);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(219, 261, 76, 16));
        lineEdit_DOE_Nosnik = new QLineEdit(DOE);
        lineEdit_DOE_Nosnik->setObjectName(QString::fromUtf8("lineEdit_DOE_Nosnik"));
        lineEdit_DOE_Nosnik->setGeometry(QRect(324, 258, 113, 20));
        tabWidget->addTab(DOE, QString());
        IOF = new QWidget();
        IOF->setObjectName(QString::fromUtf8("IOF"));
        label_24 = new QLabel(IOF);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(3, 3, 73, 16));
        lineEdit_RokProd = new QLineEdit(IOF);
        lineEdit_RokProd->setObjectName(QString::fromUtf8("lineEdit_RokProd"));
        lineEdit_RokProd->setGeometry(QRect(72, 3, 64, 20));
        label_25 = new QLabel(IOF);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(144, 3, 73, 16));
        lineEdit_CzasProj = new QLineEdit(IOF);
        lineEdit_CzasProj->setObjectName(QString::fromUtf8("lineEdit_CzasProj"));
        lineEdit_CzasProj->setGeometry(QRect(216, 3, 88, 20));
        label_26 = new QLabel(IOF);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(330, 3, 130, 16));
        lineEdit_SysKodObr = new QLineEdit(IOF);
        lineEdit_SysKodObr->setObjectName(QString::fromUtf8("lineEdit_SysKodObr"));
        lineEdit_SysKodObr->setGeometry(QRect(459, 3, 113, 20));
        label_27 = new QLabel(IOF);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(3, 24, 73, 16));
        lineEdit_DataPrem = new QLineEdit(IOF);
        lineEdit_DataPrem->setObjectName(QString::fromUtf8("lineEdit_DataPrem"));
        lineEdit_DataPrem->setGeometry(QRect(72, 24, 64, 20));
        label_28 = new QLabel(IOF);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(144, 24, 103, 16));
        lineEdit_FormWysw = new QLineEdit(IOF);
        lineEdit_FormWysw->setObjectName(QString::fromUtf8("lineEdit_FormWysw"));
        lineEdit_FormWysw->setGeometry(QRect(252, 24, 82, 20));
        label_29 = new QLabel(IOF);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(3, 48, 70, 16));
        lineEdit_JezLekt = new QLineEdit(IOF);
        lineEdit_JezLekt->setObjectName(QString::fromUtf8("lineEdit_JezLekt"));
        lineEdit_JezLekt->setGeometry(QRect(72, 45, 223, 20));
        label_30 = new QLabel(IOF);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(300, 45, 79, 16));
        lineEdit_JezNap = new QLineEdit(IOF);
        lineEdit_JezNap->setObjectName(QString::fromUtf8("lineEdit_JezNap"));
        lineEdit_JezNap->setGeometry(QRect(372, 45, 202, 20));
        groupBox_3 = new QGroupBox(IOF);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(3, 69, 187, 85));
        label_31 = new QLabel(groupBox_3);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(6, 15, 37, 16));
        lineEdit_KodVidNazwa = new QLineEdit(groupBox_3);
        lineEdit_KodVidNazwa->setObjectName(QString::fromUtf8("lineEdit_KodVidNazwa"));
        lineEdit_KodVidNazwa->setGeometry(QRect(45, 15, 130, 20));
        label_32 = new QLabel(groupBox_3);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(6, 36, 31, 16));
        lineEdit_KodVidTyp = new QLineEdit(groupBox_3);
        lineEdit_KodVidTyp->setObjectName(QString::fromUtf8("lineEdit_KodVidTyp"));
        lineEdit_KodVidTyp->setGeometry(QRect(45, 36, 130, 20));
        label_33 = new QLabel(groupBox_3);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(6, 57, 37, 16));
        lineEdit_KodVidWersja = new QLineEdit(groupBox_3);
        lineEdit_KodVidWersja->setObjectName(QString::fromUtf8("lineEdit_KodVidWersja"));
        lineEdit_KodVidWersja->setGeometry(QRect(45, 57, 130, 20));
        groupBox_4 = new QGroupBox(IOF);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        groupBox_4->setGeometry(QRect(195, 69, 190, 85));
        label_34 = new QLabel(groupBox_4);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(12, 15, 37, 16));
        label_35 = new QLabel(groupBox_4);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(12, 36, 31, 16));
        label_36 = new QLabel(groupBox_4);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(12, 57, 37, 16));
        lineEdit_KodAudNazwa = new QLineEdit(groupBox_4);
        lineEdit_KodAudNazwa->setObjectName(QString::fromUtf8("lineEdit_KodAudNazwa"));
        lineEdit_KodAudNazwa->setGeometry(QRect(51, 15, 130, 20));
        lineEdit_KodAudTyp = new QLineEdit(groupBox_4);
        lineEdit_KodAudTyp->setObjectName(QString::fromUtf8("lineEdit_KodAudTyp"));
        lineEdit_KodAudTyp->setGeometry(QRect(51, 36, 130, 20));
        lineEdit_KodAudWersja = new QLineEdit(groupBox_4);
        lineEdit_KodAudWersja->setObjectName(QString::fromUtf8("lineEdit_KodAudWersja"));
        lineEdit_KodAudWersja->setGeometry(QRect(51, 57, 130, 20));
        groupBox_5 = new QGroupBox(IOF);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        groupBox_5->setGeometry(QRect(390, 69, 184, 85));
        label_37 = new QLabel(groupBox_5);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(9, 15, 37, 16));
        lineEdit_ZabNazwa = new QLineEdit(groupBox_5);
        lineEdit_ZabNazwa->setObjectName(QString::fromUtf8("lineEdit_ZabNazwa"));
        lineEdit_ZabNazwa->setGeometry(QRect(48, 15, 130, 20));
        label_38 = new QLabel(groupBox_5);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(9, 36, 31, 16));
        lineEdit_ZabTyp = new QLineEdit(groupBox_5);
        lineEdit_ZabTyp->setObjectName(QString::fromUtf8("lineEdit_ZabTyp"));
        lineEdit_ZabTyp->setGeometry(QRect(48, 36, 130, 20));
        label_39 = new QLabel(groupBox_5);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(9, 60, 37, 16));
        lineEdit_ZabWersja = new QLineEdit(groupBox_5);
        lineEdit_ZabWersja->setObjectName(QString::fromUtf8("lineEdit_ZabWersja"));
        lineEdit_ZabWersja->setGeometry(QRect(48, 57, 130, 20));
        label_40 = new QLabel(IOF);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(6, 159, 97, 16));
        lineEdit_KrajProd = new QLineEdit(IOF);
        lineEdit_KrajProd->setObjectName(QString::fromUtf8("lineEdit_KrajProd"));
        lineEdit_KrajProd->setGeometry(QRect(108, 159, 463, 20));
        tableWidget_IOF_LZ = new QTableWidget(IOF);
        if (tableWidget_IOF_LZ->columnCount() < 8)
            tableWidget_IOF_LZ->setColumnCount(8);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        tableWidget_IOF_LZ->setHorizontalHeaderItem(0, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        tableWidget_IOF_LZ->setHorizontalHeaderItem(1, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        tableWidget_IOF_LZ->setHorizontalHeaderItem(2, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        tableWidget_IOF_LZ->setHorizontalHeaderItem(3, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        tableWidget_IOF_LZ->setHorizontalHeaderItem(4, __qtablewidgetitem31);
        QTableWidgetItem *__qtablewidgetitem32 = new QTableWidgetItem();
        tableWidget_IOF_LZ->setHorizontalHeaderItem(5, __qtablewidgetitem32);
        QTableWidgetItem *__qtablewidgetitem33 = new QTableWidgetItem();
        tableWidget_IOF_LZ->setHorizontalHeaderItem(6, __qtablewidgetitem33);
        QTableWidgetItem *__qtablewidgetitem34 = new QTableWidgetItem();
        tableWidget_IOF_LZ->setHorizontalHeaderItem(7, __qtablewidgetitem34);
        tableWidget_IOF_LZ->setObjectName(QString::fromUtf8("tableWidget_IOF_LZ"));
        tableWidget_IOF_LZ->setGeometry(QRect(3, 192, 568, 109));
        tableWidget_IOF_LZ->setEditTriggers(QAbstractItemView::DoubleClicked);
        tableWidget_IOF_LZ->setTabKeyNavigation(false);
        tableWidget_IOF_LZ->setProperty("showDropIndicator", QVariant(false));
        tableWidget_IOF_LZ->setDragDropOverwriteMode(false);
        tableWidget_IOF_LZ->setSelectionBehavior(QAbstractItemView::SelectRows);
        label_41 = new QLabel(IOF);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(6, 177, 109, 16));
        pushButton_LZSave = new QPushButton(IOF);
        pushButton_LZSave->setObjectName(QString::fromUtf8("pushButton_LZSave"));
        pushButton_LZSave->setGeometry(QRect(288, 303, 75, 23));
        pushButton_LZDel = new QPushButton(IOF);
        pushButton_LZDel->setObjectName(QString::fromUtf8("pushButton_LZDel"));
        pushButton_LZDel->setGeometry(QRect(498, 303, 75, 23));
        pushButton_LZ_New = new QPushButton(IOF);
        pushButton_LZ_New->setObjectName(QString::fromUtf8("pushButton_LZ_New"));
        pushButton_LZ_New->setGeometry(QRect(213, 303, 75, 23));
        tabWidget->addTab(IOF, QString());
        BIBLIO = new QWidget();
        BIBLIO->setObjectName(QString::fromUtf8("BIBLIO"));
        tableWidget_BIBLIO_WYPIN = new QTableWidget(BIBLIO);
        if (tableWidget_BIBLIO_WYPIN->columnCount() < 7)
            tableWidget_BIBLIO_WYPIN->setColumnCount(7);
        QTableWidgetItem *__qtablewidgetitem35 = new QTableWidgetItem();
        tableWidget_BIBLIO_WYPIN->setHorizontalHeaderItem(0, __qtablewidgetitem35);
        QTableWidgetItem *__qtablewidgetitem36 = new QTableWidgetItem();
        tableWidget_BIBLIO_WYPIN->setHorizontalHeaderItem(1, __qtablewidgetitem36);
        QTableWidgetItem *__qtablewidgetitem37 = new QTableWidgetItem();
        tableWidget_BIBLIO_WYPIN->setHorizontalHeaderItem(2, __qtablewidgetitem37);
        QTableWidgetItem *__qtablewidgetitem38 = new QTableWidgetItem();
        tableWidget_BIBLIO_WYPIN->setHorizontalHeaderItem(3, __qtablewidgetitem38);
        QTableWidgetItem *__qtablewidgetitem39 = new QTableWidgetItem();
        tableWidget_BIBLIO_WYPIN->setHorizontalHeaderItem(4, __qtablewidgetitem39);
        QTableWidgetItem *__qtablewidgetitem40 = new QTableWidgetItem();
        tableWidget_BIBLIO_WYPIN->setHorizontalHeaderItem(5, __qtablewidgetitem40);
        QTableWidgetItem *__qtablewidgetitem41 = new QTableWidgetItem();
        tableWidget_BIBLIO_WYPIN->setHorizontalHeaderItem(6, __qtablewidgetitem41);
        tableWidget_BIBLIO_WYPIN->setObjectName(QString::fromUtf8("tableWidget_BIBLIO_WYPIN"));
        tableWidget_BIBLIO_WYPIN->setGeometry(QRect(0, 15, 580, 133));
        tableWidget_BIBLIO_WYPIN->setTabKeyNavigation(false);
        tableWidget_BIBLIO_WYPIN->setProperty("showDropIndicator", QVariant(false));
        tableWidget_BIBLIO_WYPIN->setDragDropOverwriteMode(false);
        tableWidget_BIBLIO_WYPIN->setSelectionBehavior(QAbstractItemView::SelectRows);
        tableWidget_BIBLIO_WYPIN->horizontalHeader()->setDefaultSectionSize(150);
        label_42 = new QLabel(BIBLIO);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(0, 0, 151, 16));
        pushButton_BIBLIOWYPISave = new QPushButton(BIBLIO);
        pushButton_BIBLIOWYPISave->setObjectName(QString::fromUtf8("pushButton_BIBLIOWYPISave"));
        pushButton_BIBLIOWYPISave->setGeometry(QRect(351, 150, 75, 23));
        pushButton_BIBLIOWYPINDel = new QPushButton(BIBLIO);
        pushButton_BIBLIOWYPINDel->setObjectName(QString::fromUtf8("pushButton_BIBLIOWYPINDel"));
        pushButton_BIBLIOWYPINDel->setGeometry(QRect(504, 150, 75, 23));
        tableWidget_BIBLIO_WYPODIN = new QTableWidget(BIBLIO);
        if (tableWidget_BIBLIO_WYPODIN->columnCount() < 7)
            tableWidget_BIBLIO_WYPODIN->setColumnCount(7);
        QTableWidgetItem *__qtablewidgetitem42 = new QTableWidgetItem();
        tableWidget_BIBLIO_WYPODIN->setHorizontalHeaderItem(0, __qtablewidgetitem42);
        QTableWidgetItem *__qtablewidgetitem43 = new QTableWidgetItem();
        tableWidget_BIBLIO_WYPODIN->setHorizontalHeaderItem(1, __qtablewidgetitem43);
        QTableWidgetItem *__qtablewidgetitem44 = new QTableWidgetItem();
        tableWidget_BIBLIO_WYPODIN->setHorizontalHeaderItem(2, __qtablewidgetitem44);
        QTableWidgetItem *__qtablewidgetitem45 = new QTableWidgetItem();
        tableWidget_BIBLIO_WYPODIN->setHorizontalHeaderItem(3, __qtablewidgetitem45);
        QTableWidgetItem *__qtablewidgetitem46 = new QTableWidgetItem();
        tableWidget_BIBLIO_WYPODIN->setHorizontalHeaderItem(4, __qtablewidgetitem46);
        QTableWidgetItem *__qtablewidgetitem47 = new QTableWidgetItem();
        tableWidget_BIBLIO_WYPODIN->setHorizontalHeaderItem(5, __qtablewidgetitem47);
        QTableWidgetItem *__qtablewidgetitem48 = new QTableWidgetItem();
        tableWidget_BIBLIO_WYPODIN->setHorizontalHeaderItem(6, __qtablewidgetitem48);
        tableWidget_BIBLIO_WYPODIN->setObjectName(QString::fromUtf8("tableWidget_BIBLIO_WYPODIN"));
        tableWidget_BIBLIO_WYPODIN->setGeometry(QRect(0, 174, 580, 118));
        tableWidget_BIBLIO_WYPODIN->setEditTriggers(QAbstractItemView::DoubleClicked|QAbstractItemView::EditKeyPressed);
        tableWidget_BIBLIO_WYPODIN->setTabKeyNavigation(false);
        tableWidget_BIBLIO_WYPODIN->setProperty("showDropIndicator", QVariant(false));
        tableWidget_BIBLIO_WYPODIN->setDragDropOverwriteMode(false);
        tableWidget_BIBLIO_WYPODIN->setSelectionBehavior(QAbstractItemView::SelectRows);
        tableWidget_BIBLIO_WYPODIN->horizontalHeader()->setDefaultSectionSize(150);
        pushButton_BIBLIOWYPODINSave = new QPushButton(BIBLIO);
        pushButton_BIBLIOWYPODINSave->setObjectName(QString::fromUtf8("pushButton_BIBLIOWYPODINSave"));
        pushButton_BIBLIOWYPODINSave->setGeometry(QRect(354, 294, 75, 23));
        pushButton_BIBLIOWYPODINDel = new QPushButton(BIBLIO);
        pushButton_BIBLIOWYPODINDel->setObjectName(QString::fromUtf8("pushButton_BIBLIOWYPODINDel"));
        pushButton_BIBLIOWYPODINDel->setGeometry(QRect(504, 294, 75, 23));
        label_43 = new QLabel(BIBLIO);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(3, 159, 151, 16));
        pushButton_B_WYPIN_New = new QPushButton(BIBLIO);
        pushButton_B_WYPIN_New->setObjectName(QString::fromUtf8("pushButton_B_WYPIN_New"));
        pushButton_B_WYPIN_New->setGeometry(QRect(276, 150, 75, 23));
        pushButton_B_WYPODIN_New = new QPushButton(BIBLIO);
        pushButton_B_WYPODIN_New->setObjectName(QString::fromUtf8("pushButton_B_WYPODIN_New"));
        pushButton_B_WYPODIN_New->setGeometry(QRect(279, 294, 75, 23));
        tabWidget->addTab(BIBLIO, QString());
        pushButton_First = new QPushButton(centralWidget);
        pushButton_First->setObjectName(QString::fromUtf8("pushButton_First"));
        pushButton_First->setGeometry(QRect(15, 444, 46, 28));
        QFont font;
        font.setFamily(QString::fromUtf8("MS Shell Dlg 2"));
        font.setPointSize(8);
        font.setBold(true);
        font.setItalic(false);
        font.setWeight(75);
        pushButton_First->setFont(font);
        pushButton_First->setStyleSheet(QString::fromUtf8("font: bold 8pt \"MS Shell Dlg 2\";"));
        pushButton_Prev = new QPushButton(centralWidget);
        pushButton_Prev->setObjectName(QString::fromUtf8("pushButton_Prev"));
        pushButton_Prev->setGeometry(QRect(63, 444, 43, 28));
        pushButton_Prev->setFont(font);
        pushButton_Prev->setStyleSheet(QString::fromUtf8("font: bold 8pt \"MS Shell Dlg 2\";"));
        pushButton_Next = new QPushButton(centralWidget);
        pushButton_Next->setObjectName(QString::fromUtf8("pushButton_Next"));
        pushButton_Next->setGeometry(QRect(108, 444, 46, 28));
        pushButton_Next->setFont(font);
        pushButton_Next->setStyleSheet(QString::fromUtf8("font: bold 8pt \"MS Shell Dlg 2\";"));
        pushButton_Last = new QPushButton(centralWidget);
        pushButton_Last->setObjectName(QString::fromUtf8("pushButton_Last"));
        pushButton_Last->setGeometry(QRect(156, 444, 46, 28));
        pushButton_Last->setFont(font);
        pushButton_Last->setStyleSheet(QString::fromUtf8("font: bold 8pt \"MS Shell Dlg 2\";"));
        pushButton_New = new QPushButton(centralWidget);
        pushButton_New->setObjectName(QString::fromUtf8("pushButton_New"));
        pushButton_New->setGeometry(QRect(285, 444, 82, 28));
        QFont font1;
        font1.setFamily(QString::fromUtf8("MS Shell Dlg 2"));
        font1.setPointSize(8);
        font1.setItalic(false);
        pushButton_New->setFont(font1);
        pushButton_New->setCheckable(false);
        pushButton_Save = new QPushButton(centralWidget);
        pushButton_Save->setObjectName(QString::fromUtf8("pushButton_Save"));
        pushButton_Save->setGeometry(QRect(369, 444, 75, 28));
        pushButton_Save->setFont(font1);
        pushButton_Del = new QPushButton(centralWidget);
        pushButton_Del->setObjectName(QString::fromUtf8("pushButton_Del"));
        pushButton_Del->setGeometry(QRect(477, 444, 75, 28));
        pushButton_Del->setFont(font1);
        pushButton_IntWiz = new QPushButton(centralWidget);
        pushButton_IntWiz->setObjectName(QString::fromUtf8("pushButton_IntWiz"));
        pushButton_IntWiz->setGeometry(QRect(585, 444, 172, 28));
        pushButton_IntWiz->setFont(font1);
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(12, 423, 37, 16));
        lineEdit_RecNo = new QLineEdit(centralWidget);
        lineEdit_RecNo->setObjectName(QString::fromUtf8("lineEdit_RecNo"));
        lineEdit_RecNo->setGeometry(QRect(51, 420, 37, 20));
        lineEdit_RecNo->setReadOnly(true);
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(90, 423, 19, 16));
        lineEdit_RecCount = new QLineEdit(centralWidget);
        lineEdit_RecCount->setObjectName(QString::fromUtf8("lineEdit_RecCount"));
        lineEdit_RecCount->setGeometry(QRect(102, 420, 37, 20));
        lineEdit_RecCount->setReadOnly(true);
        label_44 = new QLabel(centralWidget);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(585, 9, 19, 16));
        lineEdit_ID = new QLineEdit(centralWidget);
        lineEdit_ID->setObjectName(QString::fromUtf8("lineEdit_ID"));
        lineEdit_ID->setGeometry(QRect(645, 9, 113, 20));
        lineEdit_ID->setReadOnly(true);
        label_PicFront = new QLabel(centralWidget);
        label_PicFront->setObjectName(QString::fromUtf8("label_PicFront"));
        label_PicFront->setGeometry(QRect(12, 6, 139, 172));
        label_PicFront->setFrameShape(QFrame::Box);
        label_PicFront->setScaledContents(true);
        comboBox_GatSel = new QComboBox(centralWidget);
        comboBox_GatSel->setObjectName(QString::fromUtf8("comboBox_GatSel"));
        comboBox_GatSel->setGeometry(QRect(573, 51, 187, 22));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 769, 21));
        menuOperacje = new QMenu(menuBar);
        menuOperacje->setObjectName(QString::fromUtf8("menuOperacje"));
        menuPomoc = new QMenu(menuBar);
        menuPomoc->setObjectName(QString::fromUtf8("menuPomoc"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menuOperacje->menuAction());
        menuBar->addAction(menuPomoc->menuAction());
        menuOperacje->addAction(actionOtw_rz_Utw_rz_baze_danych);
        menuOperacje->addAction(actionEksportuj);
        menuOperacje->addAction(actionWyszukaj);
        menuOperacje->addAction(actionDrukuj);
        menuOperacje->addAction(actionKoniec);
        menuPomoc->addAction(actionPomoc);
        menuPomoc->addAction(actionSprawd_aktualizacje);
        menuPomoc->addAction(actionO_programie);

        retranslateUi(MainWindow);
        QObject::connect(comboBox_GatSel, SIGNAL(currentIndexChanged(QString)), MainWindow, SLOT(on_comboBox_GatSel_currentTextChanged(QString)));

        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "Biblioteka Film\303\263w", 0, QApplication::UnicodeUTF8));
        actionOtw_rz_Utw_rz_baze_danych->setText(QApplication::translate("MainWindow", "Otw\303\263rz / Utw\303\263rz baze danych", 0, QApplication::UnicodeUTF8));
        actionEksportuj->setText(QApplication::translate("MainWindow", "Eksportuj", 0, QApplication::UnicodeUTF8));
        actionWyszukaj->setText(QApplication::translate("MainWindow", "Wyszukaj", 0, QApplication::UnicodeUTF8));
        actionKoniec->setText(QApplication::translate("MainWindow", "Koniec", 0, QApplication::UnicodeUTF8));
        actionDrukuj->setText(QApplication::translate("MainWindow", "Drukuj", 0, QApplication::UnicodeUTF8));
        actionPomoc->setText(QApplication::translate("MainWindow", "Pomoc", 0, QApplication::UnicodeUTF8));
        actionSprawd_aktualizacje->setText(QApplication::translate("MainWindow", "Sprawd\305\272 aktualizacje", 0, QApplication::UnicodeUTF8));
        actionO_programie->setText(QApplication::translate("MainWindow", "O programie", 0, QApplication::UnicodeUTF8));
        pushButton_LoadPic->setText(QApplication::translate("MainWindow", "Za\305\202aduj", 0, QApplication::UnicodeUTF8));
        pushButton_DelPic->setText(QApplication::translate("MainWindow", "Usu\305\204", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("MainWindow", "Tytu\305\202", 0, QApplication::UnicodeUTF8));
        label_2->setText(QApplication::translate("MainWindow", "Tytu\305\202 orygina\305\202u", 0, QApplication::UnicodeUTF8));
        label_3->setText(QApplication::translate("MainWindow", "Gatunek", 0, QApplication::UnicodeUTF8));
        label_45->setText(QApplication::translate("MainWindow", "Zasoby po\305\233wi\304\231cone tytu\305\202owi", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem = tableWidget_OC->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("MainWindow", "Nazwa", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidget_OC->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("MainWindow", "Tytu\305\202 tekstu", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidget_OC->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QApplication::translate("MainWindow", "Autor tekstu", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidget_OC->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QApplication::translate("MainWindow", "Strona WWW", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidget_OC->horizontalHeaderItem(4);
        ___qtablewidgetitem4->setText(QApplication::translate("MainWindow", "Ocena krytyka", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidget_OC->horizontalHeaderItem(5);
        ___qtablewidgetitem5->setText(QApplication::translate("MainWindow", "ID", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidget_OC->horizontalHeaderItem(6);
        ___qtablewidgetitem6->setText(QApplication::translate("MainWindow", "IDPDB", 0, QApplication::UnicodeUTF8));
        pushButton_OC_New->setText(QApplication::translate("MainWindow", "Nowy", 0, QApplication::UnicodeUTF8));
        pushButton_OC_Save->setText(QApplication::translate("MainWindow", "Zapisz", 0, QApplication::UnicodeUTF8));
        pushButton_OC_Del->setText(QApplication::translate("MainWindow", "Usu\305\204", 0, QApplication::UnicodeUTF8));
        groupBox_6->setTitle(QApplication::translate("MainWindow", "Ocena w\305\202asna", 0, QApplication::UnicodeUTF8));
        label_46->setText(QApplication::translate("MainWindow", "\305\232ciezka d\305\272wi\304\231kowa", 0, QApplication::UnicodeUTF8));
        label_47->setText(QApplication::translate("MainWindow", "Obsada", 0, QApplication::UnicodeUTF8));
        label_48->setText(QApplication::translate("MainWindow", "Ca\305\202o\305\233\304\207", 0, QApplication::UnicodeUTF8));
        label_49->setText(QApplication::translate("MainWindow", "Zdj\304\231cia", 0, QApplication::UnicodeUTF8));
        label_50->setText(QApplication::translate("MainWindow", "Warto\305\233\304\207 artystyczna", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("MainWindow", "Ocena", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidget_Obsada->horizontalHeaderItem(0);
        ___qtablewidgetitem7->setText(QApplication::translate("MainWindow", "Imi\304\231 i Nazwisko", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem8 = tableWidget_Obsada->horizontalHeaderItem(1);
        ___qtablewidgetitem8->setText(QApplication::translate("MainWindow", "Rola", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem9 = tableWidget_Obsada->horizontalHeaderItem(2);
        ___qtablewidgetitem9->setText(QApplication::translate("MainWindow", "ID", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem10 = tableWidget_Obsada->horizontalHeaderItem(3);
        ___qtablewidgetitem10->setText(QApplication::translate("MainWindow", "IDPDB", 0, QApplication::UnicodeUTF8));
        pushButton_OBSave->setText(QApplication::translate("MainWindow", "Zapisz", 0, QApplication::UnicodeUTF8));
        pushButton_OBDel->setText(QApplication::translate("MainWindow", "Usu\305\204", 0, QApplication::UnicodeUTF8));
        pushButton_OB_new->setText(QApplication::translate("MainWindow", "Nowy", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(obsada), QApplication::translate("MainWindow", "Obsada", 0, QApplication::UnicodeUTF8));
        label_6->setText(QApplication::translate("MainWindow", "Produkcja", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem11 = tableWidget_Prod->horizontalHeaderItem(0);
        ___qtablewidgetitem11->setText(QApplication::translate("MainWindow", "Nazwa firmy", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem12 = tableWidget_Prod->horizontalHeaderItem(1);
        ___qtablewidgetitem12->setText(QApplication::translate("MainWindow", "Adres", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem13 = tableWidget_Prod->horizontalHeaderItem(2);
        ___qtablewidgetitem13->setText(QApplication::translate("MainWindow", "Telefon", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem14 = tableWidget_Prod->horizontalHeaderItem(3);
        ___qtablewidgetitem14->setText(QApplication::translate("MainWindow", "Fax", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem15 = tableWidget_Prod->horizontalHeaderItem(4);
        ___qtablewidgetitem15->setText(QApplication::translate("MainWindow", "E-mail", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem16 = tableWidget_Prod->horizontalHeaderItem(5);
        ___qtablewidgetitem16->setText(QApplication::translate("MainWindow", "Strona WWW", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem17 = tableWidget_Prod->horizontalHeaderItem(6);
        ___qtablewidgetitem17->setText(QApplication::translate("MainWindow", "ID", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem18 = tableWidget_Prod->horizontalHeaderItem(7);
        ___qtablewidgetitem18->setText(QApplication::translate("MainWindow", "IDPDB", 0, QApplication::UnicodeUTF8));
        pushButton_PRODSave->setText(QApplication::translate("MainWindow", "Zapisz", 0, QApplication::UnicodeUTF8));
        pushButton_PRODDel->setText(QApplication::translate("MainWindow", "Usu\305\204", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem19 = tableWidget_Dystr->horizontalHeaderItem(0);
        ___qtablewidgetitem19->setText(QApplication::translate("MainWindow", "Nazwa firmy", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem20 = tableWidget_Dystr->horizontalHeaderItem(1);
        ___qtablewidgetitem20->setText(QApplication::translate("MainWindow", "Adres", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem21 = tableWidget_Dystr->horizontalHeaderItem(2);
        ___qtablewidgetitem21->setText(QApplication::translate("MainWindow", "Telefon", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem22 = tableWidget_Dystr->horizontalHeaderItem(3);
        ___qtablewidgetitem22->setText(QApplication::translate("MainWindow", "Fax", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem23 = tableWidget_Dystr->horizontalHeaderItem(4);
        ___qtablewidgetitem23->setText(QApplication::translate("MainWindow", "E-mail", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem24 = tableWidget_Dystr->horizontalHeaderItem(5);
        ___qtablewidgetitem24->setText(QApplication::translate("MainWindow", "Strona WWW", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem25 = tableWidget_Dystr->horizontalHeaderItem(6);
        ___qtablewidgetitem25->setText(QApplication::translate("MainWindow", "ID", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem26 = tableWidget_Dystr->horizontalHeaderItem(7);
        ___qtablewidgetitem26->setText(QApplication::translate("MainWindow", "IDPDB", 0, QApplication::UnicodeUTF8));
        label_7->setText(QApplication::translate("MainWindow", "Dystrybucja", 0, QApplication::UnicodeUTF8));
        pushButton_DYSTSave->setText(QApplication::translate("MainWindow", "Zapisz", 0, QApplication::UnicodeUTF8));
        pushButton_DYSTDel->setText(QApplication::translate("MainWindow", "Usu\305\204", 0, QApplication::UnicodeUTF8));
        pushButto_P_New->setText(QApplication::translate("MainWindow", "Nowy", 0, QApplication::UnicodeUTF8));
        pushButton_D_New->setText(QApplication::translate("MainWindow", "Nowy", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(Produkcja), QApplication::translate("MainWindow", "Produkcja", 0, QApplication::UnicodeUTF8));
        groupBox->setTitle(QApplication::translate("MainWindow", "W\305\202a\305\233ciciel", 0, QApplication::UnicodeUTF8));
        label_8->setText(QApplication::translate("MainWindow", "Imi\304\231", 0, QApplication::UnicodeUTF8));
        label_9->setText(QApplication::translate("MainWindow", "Nazwisko", 0, QApplication::UnicodeUTF8));
        label_10->setText(QApplication::translate("MainWindow", "Adres", 0, QApplication::UnicodeUTF8));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "Dane sklepu", 0, QApplication::UnicodeUTF8));
        label_11->setText(QApplication::translate("MainWindow", "Nazwa", 0, QApplication::UnicodeUTF8));
        label_12->setText(QApplication::translate("MainWindow", "Telefon", 0, QApplication::UnicodeUTF8));
        label_13->setText(QApplication::translate("MainWindow", "Adres", 0, QApplication::UnicodeUTF8));
        label_14->setText(QApplication::translate("MainWindow", "Strona WWW", 0, QApplication::UnicodeUTF8));
        label_15->setText(QApplication::translate("MainWindow", "Fax", 0, QApplication::UnicodeUTF8));
        label_16->setText(QApplication::translate("MainWindow", "E - mail", 0, QApplication::UnicodeUTF8));
        label_17->setText(QApplication::translate("MainWindow", "Cena", 0, QApplication::UnicodeUTF8));
        label_18->setText(QApplication::translate("MainWindow", "Warto\305\233c aktualna", 0, QApplication::UnicodeUTF8));
        label_19->setText(QApplication::translate("MainWindow", "Data zakupu", 0, QApplication::UnicodeUTF8));
        label_20->setText(QApplication::translate("MainWindow", "Data utraty", 0, QApplication::UnicodeUTF8));
        label_21->setText(QApplication::translate("MainWindow", "Data skatalogowania", 0, QApplication::UnicodeUTF8));
        label_22->setText(QApplication::translate("MainWindow", "Nr katalogowy", 0, QApplication::UnicodeUTF8));
        label_23->setText(QApplication::translate("MainWindow", "Rodzaj no\305\233nika", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(DOE), QApplication::translate("MainWindow", "Dane o egzemplarzu", 0, QApplication::UnicodeUTF8));
        label_24->setText(QApplication::translate("MainWindow", "Rok produkcji", 0, QApplication::UnicodeUTF8));
        label_25->setText(QApplication::translate("MainWindow", "Czas projekcji", 0, QApplication::UnicodeUTF8));
        label_26->setText(QApplication::translate("MainWindow", "System kodowania obrazu", 0, QApplication::UnicodeUTF8));
        label_27->setText(QApplication::translate("MainWindow", "Data premiery", 0, QApplication::UnicodeUTF8));
        label_28->setText(QApplication::translate("MainWindow", "Format wy\305\233wietlania", 0, QApplication::UnicodeUTF8));
        label_29->setText(QApplication::translate("MainWindow", "J\304\231zyk lektora", 0, QApplication::UnicodeUTF8));
        label_30->setText(QApplication::translate("MainWindow", "J\304\231zyk napis\303\263w", 0, QApplication::UnicodeUTF8));
        groupBox_3->setTitle(QApplication::translate("MainWindow", "Kodek wideo", 0, QApplication::UnicodeUTF8));
        label_31->setText(QApplication::translate("MainWindow", "Nazwa", 0, QApplication::UnicodeUTF8));
        label_32->setText(QApplication::translate("MainWindow", "Typ", 0, QApplication::UnicodeUTF8));
        label_33->setText(QApplication::translate("MainWindow", "Wersja", 0, QApplication::UnicodeUTF8));
        groupBox_4->setTitle(QApplication::translate("MainWindow", "Kodek audio", 0, QApplication::UnicodeUTF8));
        label_34->setText(QApplication::translate("MainWindow", "Nazwa", 0, QApplication::UnicodeUTF8));
        label_35->setText(QApplication::translate("MainWindow", "Typ", 0, QApplication::UnicodeUTF8));
        label_36->setText(QApplication::translate("MainWindow", "Wersja", 0, QApplication::UnicodeUTF8));
        groupBox_5->setTitle(QApplication::translate("MainWindow", "Zabezpieczenia", 0, QApplication::UnicodeUTF8));
        label_37->setText(QApplication::translate("MainWindow", "Nazwa", 0, QApplication::UnicodeUTF8));
        label_38->setText(QApplication::translate("MainWindow", "Typ", 0, QApplication::UnicodeUTF8));
        label_39->setText(QApplication::translate("MainWindow", "Wersja", 0, QApplication::UnicodeUTF8));
        label_40->setText(QApplication::translate("MainWindow", "Kraj produkcji filmu", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem27 = tableWidget_IOF_LZ->horizontalHeaderItem(0);
        ___qtablewidgetitem27->setText(QApplication::translate("MainWindow", "Nazwa obiektu", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem28 = tableWidget_IOF_LZ->horizontalHeaderItem(1);
        ___qtablewidgetitem28->setText(QApplication::translate("MainWindow", "Kraj", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem29 = tableWidget_IOF_LZ->horizontalHeaderItem(2);
        ___qtablewidgetitem29->setText(QApplication::translate("MainWindow", "Miejscowo\305\233\304\207", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem30 = tableWidget_IOF_LZ->horizontalHeaderItem(3);
        ___qtablewidgetitem30->setText(QApplication::translate("MainWindow", "Region", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem31 = tableWidget_IOF_LZ->horizontalHeaderItem(4);
        ___qtablewidgetitem31->setText(QApplication::translate("MainWindow", "Pora roku", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem32 = tableWidget_IOF_LZ->horizontalHeaderItem(5);
        ___qtablewidgetitem32->setText(QApplication::translate("MainWindow", "Data", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem33 = tableWidget_IOF_LZ->horizontalHeaderItem(6);
        ___qtablewidgetitem33->setText(QApplication::translate("MainWindow", "ID", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem34 = tableWidget_IOF_LZ->horizontalHeaderItem(7);
        ___qtablewidgetitem34->setText(QApplication::translate("MainWindow", "IDPDB", 0, QApplication::UnicodeUTF8));
        label_41->setText(QApplication::translate("MainWindow", "Lokalizacje zdj\304\231ciowe", 0, QApplication::UnicodeUTF8));
        pushButton_LZSave->setText(QApplication::translate("MainWindow", "Zapisz", 0, QApplication::UnicodeUTF8));
        pushButton_LZDel->setText(QApplication::translate("MainWindow", "Usu\305\204", 0, QApplication::UnicodeUTF8));
        pushButton_LZ_New->setText(QApplication::translate("MainWindow", "Nowy", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(IOF), QApplication::translate("MainWindow", "Info o filmie", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem35 = tableWidget_BIBLIO_WYPIN->horizontalHeaderItem(0);
        ___qtablewidgetitem35->setText(QApplication::translate("MainWindow", "Osoba", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem36 = tableWidget_BIBLIO_WYPIN->horizontalHeaderItem(1);
        ___qtablewidgetitem36->setText(QApplication::translate("MainWindow", "Data wypo\305\274yczenia", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem37 = tableWidget_BIBLIO_WYPIN->horizontalHeaderItem(2);
        ___qtablewidgetitem37->setText(QApplication::translate("MainWindow", "Data oddania", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem38 = tableWidget_BIBLIO_WYPIN->horizontalHeaderItem(3);
        ___qtablewidgetitem38->setText(QApplication::translate("MainWindow", "Stan przed wypo\305\274yczeniem", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem39 = tableWidget_BIBLIO_WYPIN->horizontalHeaderItem(4);
        ___qtablewidgetitem39->setText(QApplication::translate("MainWindow", "Stan po oddaniu", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem40 = tableWidget_BIBLIO_WYPIN->horizontalHeaderItem(5);
        ___qtablewidgetitem40->setText(QApplication::translate("MainWindow", "ID", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem41 = tableWidget_BIBLIO_WYPIN->horizontalHeaderItem(6);
        ___qtablewidgetitem41->setText(QApplication::translate("MainWindow", "IDPDB", 0, QApplication::UnicodeUTF8));
        label_42->setText(QApplication::translate("MainWindow", "Wypo\305\274yczenia innym osobom", 0, QApplication::UnicodeUTF8));
        pushButton_BIBLIOWYPISave->setText(QApplication::translate("MainWindow", "Zapisz", 0, QApplication::UnicodeUTF8));
        pushButton_BIBLIOWYPINDel->setText(QApplication::translate("MainWindow", "Usu\305\204", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem42 = tableWidget_BIBLIO_WYPODIN->horizontalHeaderItem(0);
        ___qtablewidgetitem42->setText(QApplication::translate("MainWindow", "Osoba", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem43 = tableWidget_BIBLIO_WYPODIN->horizontalHeaderItem(1);
        ___qtablewidgetitem43->setText(QApplication::translate("MainWindow", "Data wypo\305\274yczenia", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem44 = tableWidget_BIBLIO_WYPODIN->horizontalHeaderItem(2);
        ___qtablewidgetitem44->setText(QApplication::translate("MainWindow", "Data oddania", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem45 = tableWidget_BIBLIO_WYPODIN->horizontalHeaderItem(3);
        ___qtablewidgetitem45->setText(QApplication::translate("MainWindow", "Stan przed wypo\305\274yczeniem", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem46 = tableWidget_BIBLIO_WYPODIN->horizontalHeaderItem(4);
        ___qtablewidgetitem46->setText(QApplication::translate("MainWindow", "Stan po oddaniu", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem47 = tableWidget_BIBLIO_WYPODIN->horizontalHeaderItem(5);
        ___qtablewidgetitem47->setText(QApplication::translate("MainWindow", "ID", 0, QApplication::UnicodeUTF8));
        QTableWidgetItem *___qtablewidgetitem48 = tableWidget_BIBLIO_WYPODIN->horizontalHeaderItem(6);
        ___qtablewidgetitem48->setText(QApplication::translate("MainWindow", "IDPDB", 0, QApplication::UnicodeUTF8));
        pushButton_BIBLIOWYPODINSave->setText(QApplication::translate("MainWindow", "Zapisz", 0, QApplication::UnicodeUTF8));
        pushButton_BIBLIOWYPODINDel->setText(QApplication::translate("MainWindow", "Usu\305\204", 0, QApplication::UnicodeUTF8));
        label_43->setText(QApplication::translate("MainWindow", "Wypo\305\274yczenia od innych os\303\263b", 0, QApplication::UnicodeUTF8));
        pushButton_B_WYPIN_New->setText(QApplication::translate("MainWindow", "Nowy", 0, QApplication::UnicodeUTF8));
        pushButton_B_WYPODIN_New->setText(QApplication::translate("MainWindow", "Nowy", 0, QApplication::UnicodeUTF8));
        tabWidget->setTabText(tabWidget->indexOf(BIBLIO), QApplication::translate("MainWindow", "Bibliotekarz", 0, QApplication::UnicodeUTF8));
        pushButton_First->setText(QApplication::translate("MainWindow", "|<", 0, QApplication::UnicodeUTF8));
        pushButton_Prev->setText(QApplication::translate("MainWindow", "<", 0, QApplication::UnicodeUTF8));
        pushButton_Next->setText(QApplication::translate("MainWindow", ">", 0, QApplication::UnicodeUTF8));
        pushButton_Last->setText(QApplication::translate("MainWindow", ">|", 0, QApplication::UnicodeUTF8));
        pushButton_New->setText(QApplication::translate("MainWindow", "Nowy", 0, QApplication::UnicodeUTF8));
        pushButton_Save->setText(QApplication::translate("MainWindow", "Zapisz", 0, QApplication::UnicodeUTF8));
        pushButton_Del->setText(QApplication::translate("MainWindow", "Usu\305\204", 0, QApplication::UnicodeUTF8));
        pushButton_IntWiz->setText(QApplication::translate("MainWindow", "Pobierz z Internetu", 0, QApplication::UnicodeUTF8));
        label_4->setText(QApplication::translate("MainWindow", "Rekord", 0, QApplication::UnicodeUTF8));
        label_5->setText(QApplication::translate("MainWindow", "z", 0, QApplication::UnicodeUTF8));
        label_44->setText(QApplication::translate("MainWindow", "ID", 0, QApplication::UnicodeUTF8));
        label_PicFront->setText(QString());
        comboBox_GatSel->clear();
        comboBox_GatSel->insertItems(0, QStringList()
         << QString()
         << QApplication::translate("MainWindow", "Akcja", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("MainWindow", "Krymina\305\202", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("MainWindow", "Sensacyjny", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("MainWindow", "Komedia", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("MainWindow", "Dramat", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("MainWindow", "Fabularny", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("MainWindow", "Dokumentalny", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("MainWindow", "Paradokument", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("MainWindow", "Reporta\305\274", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("MainWindow", "Sci-Fi", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("MainWindow", "Fantastyka", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("MainWindow", "Bajka", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("MainWindow", "Kresk\303\263wka", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("MainWindow", "Erotyka", 0, QApplication::UnicodeUTF8)
         << QApplication::translate("MainWindow", "Porno", 0, QApplication::UnicodeUTF8)
        );
        menuOperacje->setTitle(QApplication::translate("MainWindow", "Operacje", 0, QApplication::UnicodeUTF8));
        menuPomoc->setTitle(QApplication::translate("MainWindow", "Pomoc", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
